### ISSUE TITLE
Add opacity settings

### ISSUE THREAD

**Issue by ai** [zhanghai/gnome-shell-extension-transparent-top-bar#1]
I want to have `0` opacity when there is no full-screen window. Can we add settings for it?

**Comment by DreaminginCodeZH** [comment]
You might be more interested in https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/404

This extension is a simple port of the removed original feature implementation, so for now I don't have any plan to add all kinds of settings :/

**Comment by ai** [comment]
Thanks. I subscribed for that issue.

if you do not want to add this feature you can close the issue (I understand that you want to be more focused on exact behaviour).

**Comment by aunetx** [comment]
Hi, I wanted that feature too so I made a fork.
You you can check it at [https://github.com/aunetx/gnome-shell-extension-transparent-top-bar](https://github.com/aunetx/gnome-shell-extension-transparent-top-bar) (available on [extensions.gnome.org](https://extensions.gnome.org/extension/2588/fully-transparent-top-bar/) too)
By the way, thanks to the maintainer of this extension !

**Comment by rdsngit** [comment]
> Hi, I wanted that feature too so I made a fork.
> You you can check it at https://github.com/aunetx/gnome-shell-extension-transparent-top-bar (available on [extensions.gnome.org](https://extensions.gnome.org/extension/2588/fully-transparent-top-bar/) too)
> By the way, thanks to the maintainer of this extension !

I tried this extension, also felt it would benefit from transparency settings. @aunetx your forked extension works great on Pop!_OS 20.04 for transparency in the overview and desktop

**Comment by zhanghai** [comment]
Not going to support this to keep this project minimal.
