### ISSUE TITLE
Top Bar Curved Corners Have Different Opacity in Gnome 40

### ISSUE THREAD

**Issue by kdwk** [zhanghai/gnome-shell-extension-transparent-top-bar#11]
The Gnome top bar has two corners that curve downwards. However, when the rest of the top bar is transparent, the corners have a different opacity than the rest of it.
Affected version: 
![Screenshot from 2021-02-06 09-50-48](https://user-images.githubusercontent.com/39268094/107105362-d71bbb00-6860-11eb-8e2e-8e783e383878.png)  Wayland

Problem:
![Screenshot from 2021-01-24 21-26-13](https://user-images.githubusercontent.com/39268094/107105337-b5223880-6860-11eb-84db-047b3bc763b2.png)

**Comment by zhanghai** [comment]
Your screenshot doesn't look like the opacity for the corner is wrong - but that it has some overlap with the top bar itself. I don't think I can do anything here and maybe you should raise the issue to GNOME Shell.

**Comment by yw662** [comment]
Maybe this can be done by set corner transparent to 0 for -transparent class, and set it back for -solid.

**Comment by zhanghai** [comment]
FYI this has been fixed in [the latest version](https://extensions.gnome.org/extension/1708/transparent-top-bar/), please try it out!
