### ISSUE TITLE
[Gnome 40] Maybe don't make it --transparent in overview mode, when shell version is 40.

### ISSUE THREAD

**Issue by yw662** [zhanghai/gnome-shell-extension-transparent-top-bar#17]
https://github.com/zhanghai/gnome-shell-extension-transparent-top-bar/blob/0d95836a7594085f2df6bcdebd9010f1f1144002/src/extension.js#L71

Gnome 40 would set the color of top bar to sth other than black:
![image](https://user-images.githubusercontent.com/34736747/116529979-5d5d0180-a892-11eb-96bc-1e5612f2d001.png)
However with this extension enabled, it would be like this:
![image](https://user-images.githubusercontent.com/34736747/116530114-81b8de00-a892-11eb-964c-f40d2714dc8d.png)

Since the color is already set by gnome, maybe it is better to keep its default behavior.

**Comment by zhanghai** [comment]
I'll take a look at this when I upgrade to 40 - a number of extensions I use is still broken on 40 so I'm postponing my update.
