### ISSUE TITLE
Top bar not transparent with Desktop Icons NG extention enabled

### ISSUE THREAD

**Issue by JannekeNouwen** [zhanghai/gnome-shell-extension-transparent-top-bar#19]
The top bar is not transparent whenever I have the Desktop Icons NG extension enabled. When turning all extensions on and off, the top bar is transparent for a second, and goes back to black when the desktop icons are loaded. My guess is that the top bar extension thinks of the desktop extension as a maximized window?
I use Manjaro 12.1 and GNOME 40.3

**Comment by zhanghai** [comment]
Yes, likely. I want to keep this extension simple and don't have the plan to add compatibility code for one (or many) specific extensions, so feel free to fork this and add your own modifications. You may also reach out to [an existing fork of this extension](https://github.com/lamarios/gnome-shell-extension-transparent-top-bar) and see if they are willing to take on maintaining this.
