### ISSUE TITLE
How do I adjust the transparency of the top bar?

### ISSUE THREAD

**Issue by VihagChaturvedi** [zhanghai/gnome-shell-extension-transparent-top-bar#23]
Hello!

I have recently started using this extension on Gnome 41, I previously used to use a fork of this repo which had the option of changing the transparency using the extensions settings itself

Unfortunately, this extension doesnt seem to have a similar option.

How can I manually adjust the transparency of the top bar using this current extension if I wish to?

Thank you!

**Comment by zhanghai** [comment]
Sorry but you can't - I'm intending to keep the things minimal here (just what I personally need) so that I can keep maintaining this project in the long run. If you want transparency adjustment, I think you need to use the fork that comes with more features.
