### ISSUE TITLE
fully black in gnome 41

### ISSUE THREAD

**Issue by hemcharan22** [zhanghai/gnome-shell-extension-transparent-top-bar#25]
in gnome 41 the transparent bar is fully black 

![Screenshot from 2021-12-23 10-32-21](https://user-images.githubusercontent.com/77770865/147190593-61731f45-64c5-4309-83a2-e6f3e8434304.png)

**Comment by zhanghai** [comment]
It's only transparent when you don't have any maximized window. This is the behavior of the original GNOME She'll implementation.
