### ISSUE TITLE
Not working on Ubuntu 21.10

### ISSUE THREAD

**Issue by johndzxu** [zhanghai/gnome-shell-extension-transparent-top-bar#29]
Hi, my top panel doesn't become transparent after I installed this extension. I am using Ubuntu 21.10 with Wayland. Is Wayland supported?

**Comment by zhanghai** [comment]
Wayland is supported (I don't think there's anything in this extension specific to X11 or Wayland), but I'm not sure if Ubuntu GNOME is supported - maybe they made customizations to GNOME?

**Comment by johndzxu** [comment]
I said Wayland because if I use X11 instead this extension works perfectly. Below is a list of custom Gnome extensions I have if that helps. Also, I've tried disabling all extensions except this one and the default ones in case their are some conflicts, but that didn't fix the issue.
![Screenshot from 2022-04-08 19-52-09](https://user-images.githubusercontent.com/77399093/162431556-22374679-6133-4950-961c-52bcaf6886c9.png)

**Comment by johndzxu** [comment]
Good news I found out that the problem is with the built-in extension [Desktop Icons NG].  (https://extensions.gnome.org/extension/2087/desktop-icons-ng-ding/) When I turn it off this extension worked. However, that extension is too important to remove so could you add try to resolve the conflict please.
