### ISSUE TITLE
JS ERROR: TypeError: this._windowSignalIds.get(...) is undefined

### ISSUE THREAD

**Issue by peterlobster** [zhanghai/gnome-shell-extension-transparent-top-bar#31]
I observed this coming up in my logs...

```shell
Aug 06 10:55:19 localhost gnome-shell[1707]: JS ERROR: TypeError: this._windowSignalIds.get(...) is undefined
                                      _onWindowActorRemoved@/home/peter/.local/share/gnome-shell/extensions/transparent-top-bar@ftpix.com/extension.js:112:54
                                      _initializeUI/<@resource:///org/gnome/shell/ui/main.js:251:16
```

**Comment by zhanghai** [comment]
What is your OS version, GNOME Shell version and extension version?

**Comment by peterlobster** [comment]
OS - Gentoo
```shell
$ uname -r
5.19.0-gentoo
```

GNOME Shell
```
$ gnome-shell --version
GNOME Shell 42.3.1
```

Extension Version: 12

**Comment by zhanghai** [comment]
That's weird, I've been using Arch Linux with GNOME Shell (now 42.4), and I've never encountered this. Looking at the code, `this._windowSignalIds` should always be a `Map` or `null`, but the error is saying the `get` is undefined instead of `_windowSignalIds` itself, so I'm confused...
