### ISSUE TITLE
Cannot find this extension via GNOME Software?

### ISSUE THREAD

**Issue by JaneSmith** [zhanghai/gnome-shell-extension-transparent-top-bar#4]
Hello. I'm having some trouble installing this extension. I'd like to install it via GNOME Software, but for some reason it doesn't come up in a search. Any idea why this might be?

I can of course see the extension webpage via my browser, but if I search for it (e.g. "transparent", "transparent top bar", "zhanghai", etc.) it doesn't come up. There is another, older extension with the same name which does come up.

I'm running GNOME 3.34. Could it be because this extension is targeting 3.32? Any advice? Thanks.

**Comment by zhanghai** [comment]
Thanks! Added `3.34`.

**Comment by JaneSmith** [comment]
Thanks for updating the supported version. I still can't find the extension with GNOME Software though, using Fedora Silverblue 31 with GNOME 3.34.2-1.

Any idea why this could be? I don't know enough about how hosted extensions work. Is there a time delay before your changes get pushed to the extension repository? Or is this more likely to be a bug in GNOME Software?

**Comment by zhanghai** [comment]
Sorry, I don't use GNOME Software and usually just install from website. It does show up on website when I selected `Compatible with: Current version`, and I'm running 3.34.3, so maybe a delay in GNOME Software?
