### ISSUE TITLE
Request: Support for GNOME 3.36

### ISSUE THREAD

**Issue by Scotty-Trees** [zhanghai/gnome-shell-extension-transparent-top-bar#5]
GNOME 3.36 is going to be released March 11 and I like your extension very much and hope it can be updated to include support for GNOME 3.36. Keep up the great work!

**Comment by zhanghai** [comment]
Could you test if it works on 3.36? I don't have it in Arch yet.

**Comment by Scotty-Trees** [comment]
I use Solus GNOME 3.34 unstable edition. We'll be building 3.36 this week/next week so I can definitely test it out then and let you know!

**Comment by atifchy** [comment]
It works fine on GNOME 3.36.

**Comment by zhanghai** [comment]
Thanks for the confirmation! Added `3.36`.

(Actually GNOME 3.36 is available on Arch now, but I'm postponing my own update due to incompatibility in other extensions.)
