### ISSUE TITLE
Remove transparency only if the window is maximized instead of by proximity

### ISSUE THREAD

**Issue by daquinons** [zhanghai/gnome-shell-extension-transparent-top-bar#6]
I really like Elementary OS and its smart transparent top panel.

One of the features they have is that they make the top panel solid only when a window is full screen. This makes sense because it's when you lose any context of the desktop, and when you want to focus on only one thing. If you have open only a small window, and that window is touching the top bar, the transparency is not really something that disturbs you.

I've successfully implemented this easily editing the source code of the extension, but I'm wondering if you would be open to a PR to add this behaviour, maybe as an optional setting.

**Comment by daquinons** [comment]
In case someone wants to try the new behaviour (which personally I find it more pleasant), you can find my fork here https://github.com/daquinons/gnome-shell-extension-transparent-top-bar

**Comment by zhanghai** [comment]
Not going to support this to keep this project minimal.
